export const API = {
  groupSportsBook: "",
  banner: "",
  eventDetails: "",
  login: "",
  bankAccount: "",
  balance: "",
  otp: "",
  whatsApp: "",
  register: "",
  uploadScreenshot: "",
  buttonValue: "",
  changePassword: "",
  liveCasinoIFrame: "",
  exposure: "",
  currentBets: "",
  order: "",
  accountStatement: "",
  settledBets: "",
  indiaCardGames: "",
  assets: "",
  internationalCasino: "",
  slots: "",
  homeCasino: "",
  depositBreakdown: "",
  withdrawBreakdown: "",
  accessToken: "",
  ladder: "",
  forgotPassword:"",
  siteSettings: "",
  otpless:"",
  casinoGames:"",
  pg:"",
  pgStatus:""
};

export const Settings = {
  siteUrl: "",
  interval: "",
  siteTitle: "",
  referral: "",
  balanceApiLoop: "",
  register: "",
  otp: "",
  disabledDevtool: "",
  apkLink:"",
  casinoCurrency:"",
  chaportAppId:"",
  otpless:"",
  paymentIntent:""
};
